version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    volumes:
        - data-volume:/var/run/postgresql/data
    expose: 
      - "5432"
      - "54321:5432"
  
  server:
    user: root
    build: ./src
    command: bash -c "cd /temp && chmod o+x run.sh && ./run.sh"
    volumes:
      - ./src:/temp
    ports:
      - "12345:12345"
    depends_on: 
      - db

  